import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, apiUrl, asPage, json } from '../api'
import { Empty, Field, Notice, Page, Progress, StatusBadge } from '../components'
import { validateWorkbook } from './ImageDownloader'

type Issue = { severity?: 'error' | 'warning'; blocking?: boolean; message: string; row?: number }
export type Preflight = { id: string; rows: number; groups: number; image_urls: number; issues: Issue[]; valid: boolean }
type Run = { id: string; name?: string; status: string; completed_items?: number; total_items?: number; failed_items?: number; created_at?: string; deleted_at?: string }
export const blockingIssues = (preflight: Preflight) => preflight.issues.filter(issue => issue.blocking ?? issue.severity === 'error').length

export function RunsPage() {
  const client = useQueryClient()
  const [file, setFile] = useState<File>()
  const [preflight, setPreflight] = useState<Preflight>()
  const runs = useQuery({ queryKey: ['runs'], queryFn: () => api('/runs?page_size=50&include_deleted=true').then(value => asPage(value as Run[])), refetchInterval: 4000 })
  const inspect = useMutation({ mutationFn: async () => { const error = validateWorkbook(file); if (error) throw new Error(error); const body = new FormData(); body.append('file', file!); return api<Preflight>('/preflight', { method: 'POST', body }) }, onSuccess: setPreflight })
  const start = useMutation({ mutationFn: () => api<Run>('/runs', json('POST', { name: file?.name.replace(/\.[^.]+$/, '') || 'Catalog run', preflight_id: preflight?.id })), onSuccess: () => { setPreflight(undefined); setFile(undefined); client.invalidateQueries({ queryKey: ['runs'] }) } })
  const control = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => action === 'delete' ? api(`/runs/${id}`, { method: 'DELETE' }) : api(`/runs/${id}/${action}`, json('POST')), onSuccess: () => client.invalidateQueries({ queryKey: ['runs'] }) })
  const submit = (event: FormEvent) => { event.preventDefault(); inspect.mutate() }
  return <Page title="Runs" description="Preflight validates the workbook without calling an LLM." actions={<a className="btn-secondary" href={apiUrl('/templates/workbook')}>Download template</a>}>
    {(inspect.isError || start.isError || control.isError) && <Notice tone="error">{(inspect.error || start.error || control.error)?.message}</Notice>}
    <form className="card flex flex-wrap items-end gap-3" onSubmit={submit}><div className="min-w-64 flex-1"><Field label="Catalog workbook" hint="Headers and base-code groups are checked before a run exists."><input className="control" type="file" accept=".xlsx,.xlsm" required onChange={e => { setFile(e.target.files?.[0]); setPreflight(undefined) }} /></Field></div><button className="btn-primary" disabled={inspect.isPending}>{inspect.isPending ? 'Checking…' : 'Run preflight'}</button></form>
    {preflight && <div className="card space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">Preflight summary</h2><p className="text-sm text-slate-600">{preflight.rows} rows · {preflight.groups} base-code groups · {preflight.image_urls} image URLs</p></div><StatusBadge value={blockingIssues(preflight) ? 'blocked' : 'ready'} /></div>{preflight.issues.length ? <ul className="space-y-2">{preflight.issues.map((issue, index) => <li key={index} className={`rounded-lg p-3 text-sm ${issue.blocking ?? issue.severity === 'error' ? 'bg-red-50 text-red-800' : 'bg-amber-50 text-amber-900'}`}>{issue.row ? `Row ${issue.row}: ` : ''}{issue.message}</li>)}</ul> : <Notice tone="success">No issues found.</Notice>}<button className="btn-primary" disabled={Boolean(blockingIssues(preflight)) || start.isPending} onClick={() => start.mutate()}>{start.isPending ? 'Starting…' : 'Start run'}</button></div>}
    <div className="card"><h2 className="mb-4 font-bold">Recent runs</h2>{runs.isPending ? <p>Loading…</p> : runs.isError ? <Notice tone="error">{runs.error.message}</Notice> : !runs.data.items.length ? <Empty>No catalog runs yet.</Empty> : <div className="divide-y divide-slate-200">{runs.data.items.map(run => { const progress = run.total_items ? (run.completed_items || 0) / run.total_items * 100 : 0; return <article key={run.id} className="grid gap-3 py-4 md:grid-cols-[minmax(12rem,1fr)_minmax(12rem,1fr)_auto] md:items-center"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{run.name || `Run ${run.id.slice(0, 8)}`}</h3><StatusBadge value={run.deleted_at ? 'deleted' : run.status} /></div>{run.created_at && <p className="text-xs text-slate-500">{new Date(run.created_at).toLocaleString()}</p>}</div><Progress value={progress} label={`${run.completed_items || 0} of ${run.total_items || 0} items`} /><div className="flex flex-wrap gap-2">{!run.deleted_at && <Link className="btn-secondary" to={`/review?run=${encodeURIComponent(run.id)}`}>Review</Link>}{['queued', 'running', 'cancelling'].includes(run.status) && <button className="btn-danger" onClick={() => control.mutate({ id: run.id, action: 'cancel' })}>Cancel</button>}{['failed', 'cancelled'].includes(run.status) && <button className="btn-secondary" onClick={() => control.mutate({ id: run.id, action: run.status === 'failed' ? 'retry' : 'resume' })}>{run.status === 'failed' ? 'Retry' : 'Resume'}</button>}{run.deleted_at ? <button className="btn-secondary" onClick={() => control.mutate({ id: run.id, action: 'restore' })}>Restore</button> : <><button className="btn-secondary" onClick={() => control.mutate({ id: run.id, action: 'duplicate' })}>Duplicate</button><button className="btn-danger" onClick={() => control.mutate({ id: run.id, action: 'delete' })}>Delete</button></>}</div></article> })}</div>}</div>
  </Page>
}
